<?php
//Demo tính trừu tượng (tạo một lớp trừu tượng Sinhvien)
abstract class Sinhvien{
    private $MSSV;
    private $NameSV;
    private $Age;

    public function getMSSV()
    {
        return $this->MSSV;
    }
    public function setMSSV($MSSV)
    {
        $this->MSSV = $MSSV;
    }
    public function getNameSV()
    {
        return $this->NameSV;
    }
    public function setNameSV($NameSV)
    {
        $this->NameSV = $NameSV;
    }
    public function getAge()
    {
        return $this->Age;
    }
    public function setAge($Age)
    {
        $this->Age = $Age;
    }
    abstract public function dangkymonhoc();//phương thức trừu tượng dangkymonhoc()
    abstract public function dithi();//phương thức trừu tượng dithi()
    public function NhanHB(){
        echo "Sinh vien nhan hoc bong cua truong";
    }
}


//Demo tính kế thừa
 class SV_CNTT extends Sinhvien{

    public function dangkymonhoc()
    {
        // TODO: Implement dangkymonhoc() method.
        echo "SV_CNTT dang ky mon hoc";

    }
    public function dithi()
    {
        // TODO: Implement dithi() method.
        echo "SV_CNTT di thi";
    }
    public function NhanHB()
    {
        //parent::NhanHB(); // TODO: Change the autogenerated stub
        echo "<br />Sinh vien khoa CNTT nhan hoc bong cua khoa";
    }
 }

$SVCNTT = new SV_CNTT();

$SVCNTT->NhanHB();

//$SV = new Sinhvien();